config/routes.rb
DelayedJobDemo::Application.routes.draw do
  resources :mailings do
    member { post :deliver }
  end

   root :to => 'mailings#index'

end

app/models/mail_job.rb
class MailJob < Struct.new(:id)
  include ApplicationHelper

  def enqueue(job)
    log_worker_msg(job, id,  "[ENQUEUE] mail_job has been put into the queue")
  end

  def perform
    log_worker_msg(nil, id,  "[PERFORM] mail_job is performing the 'deliver' task...")
    Mailing.deliver(id)
  end

  def before(job)
    log_worker_msg(job, id, "[START] mail_job is starting!")
  end

  def after(job)
    log_worker_msg(job, id, "[FINISH] mail_job has finished.")
  end

  def success(job)
    log_worker_msg(job, id, "[SUCCESS] mail_job was successful")
  end

  def error(job, exception)
    log_worker_msg(job, id, "[ERROR] mail_job encountered an error:  #{ exception.message }")
    #Airbrake.notify(exception)
  end

  def failure
    log_worker_msg(nil, id, "[FAIL] mail_job failed.")
  end
end

app/models/mailing.rb
class Mailing < ActiveRecord::Base
  attr_accessible :body, :delivered_at, :subject

  validates :subject, :presence => true,
                      :length => { :minimum => 5, :maximum => 50 }

  validates :body, :presence => true,
                   :length => { :minimum => 10 }

  def self.deliver(id)
    find(id).deliver
  end

  def deliver
    sleep 10
    update_attribute(:delivered_at, Time.zone.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mailings_controller.rb
class MailingsController < ApplicationController
  include ApplicationHelper
  respond_to :js, :html

  def deliver
    #Mailing.delay(:queue => "test").deliver(params[:id])
    Delayed::Job.enqueue MailJob.new(params[:id])

    redirect_to(mailings_path, :notice => "You bet your sweet ass we're spamming the HELL outta our subscribers!")
  end


  def index
    @mailings = Mailing.all()
                       #.paginate(:per_page => 10)
  end

  def show
    @mailing = Mailing.find_by_id(params[:id])
  end


  def new
    @mailing = Mailing.new
  end

  def create
    @mailing = Mailing.new(params[:mailing])

    if @mailing.save
      redirect_to(mailings_path, :notice => "Mailing <b>'#{ @mailing.subject }'</b> has been created successfully.")
    else
      render(:new, :error => @mailing.errors)
    end
  end


  def edit
    @mailing = Mailing.find_by_id(params[:id])
  end

  def update
    @mailing = Mailing.find_by_id(params[:id])

    if @mailing.update_attributes(params[:mailing])
      redirect_to(mailings_path, :notice => "Mailing <b>'#{ @mailing.subject }'</b> has been updated successfully.")
    else
      render(:edit, :error => @mailing.errors)
    end
  end


  def destroy
    @mailing = Mailing.find_by_id(params[:id])

    if @mailing.destroy
      redirect_to(mailings_path, :notice => "Mailing <b>'#{ @mailing.subject }'</b> has been deleted successfully.")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def log_worker_msg(job, id, msg, level = Logger::INFO)
    log_message = format_msg(job, id, msg)
    Delayed::Worker.logger.add(level, "#{Time.now.strftime('%FT%T%z')}: #{ log_message }")
    broadcast_message("/messages/new", log_message)
  end

def broadcast_message(channel, msg)
  begin
    Delayed::Worker.logger.debug("[DEBUG] Attempting to broadcast a log message...")

    message = { :channel => channel, :data => msg, :ext => { :auth_token => FAYE_TOKEN } }
    uri = URI.parse("http://localhost:9292/faye")
    Net::HTTP.post_form(uri, :message => message.to_json)
  rescue => e
    Delayed::Worker.logger.error("[DEBUG] [ERROR] Failed to broadcast message.  Error: #{ e.to_s }")
  ensure
    Delayed::Worker.logger.debug("[DEBUG] Attempt complete.")
  end
end

  private

    def format_msg(job, id, text)
      "[#{ job.nil? ? "<not provided>" : job.name } #{ id }, host:#{ Socket.gethostname } pid:#{ Process.pid }] #{ text }"
    end
end

app/helpers/mailings_helper.rb
module MailingsHelper


end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error alert-block">
        The form contains <%= pluralize(object.errors.count, "error") %>.
        <ul>
          <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %> fadeout">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg.html_safe, :id => "flash_#{ name }" if msg.is_a?(String) %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spamalot! Email Campaign Manager:  Delayed Job Demo</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>

<body>
    <div class="container">
      <div class="row">
        <div class="span10">
          <div style="text-align: center;">
            <%= render('layouts/messages') %>
          </div>
          <div id="content">
            <%= yield %>
          </div>
          <div id="log">
            <h3>Log Entries</h3>
            <ul style="list-style: none;"></ul>
          </div>
        </div>
      </div>
    </div>
</body>

<%= javascript_include_tag "application", "http://localhost:9292/faye.js" %>
</html>

app/views/mailings/_form.html.erb
<%= form_for(@mailing) do |f| %>
    <fieldset>
    <legend></legend>
      <%= render('layouts/error_messages', :object => f.object) %>
    <% unless @mailing.delivered_at.nil? %>
        <div>
            <small class="muted">This mailing was last delivered at <%= @mailing.delivered_at %></small>
        </div>
    <% end %>

  <div class="control-group">
    <%= f.label(:subject, :class => "control-label") %>
    <div class="controls">
      <%= f.text_field(:subject, :class => "input-xlarge") %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label(:body, :class => "control-label") %>
    <div class="controls">
      <%= f.text_area(:body, :class => "input-xlarge", :rows => 10) %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit("Save", :class=>"btn btn-primary", :role => "button", :title => "Save this mailing.") %>
    <%= submit_tag("Cancel", :class => "btn btn-inverse", :role => "button", :title => "Discard changes and return to the Home screen.", :confirm => "Are you sure you want to discard the changes to this mailing?") %>
  </div>
  </fieldset>
<% end %>

app/views/mailings/_log_display.html.erb
<li><%=  %></li>

app/views/mailings/_mailings_table.html.erb
<table class="table table-hover table-striped table-bordered">
  <thead>
  <tr>
    <th>Subject</th>
    <th>Last Delivered Date/Time</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% campaigns.each do |m| %>
      <tr>
        <td><%= m.subject %></td>
        <td><%= m.delivered_at ||= '<span class="muted"><em>never delivered</em></span>'.html_safe %></td>
        <td style="text-align: center;"><%= link_to('<i class="icon-envelope"'.html_safe, deliver_mailing_path(m), :method => :post, :data => { :remote => true }, :title => "Spam the hell outta the subscribers!") %></td>
        <td style="text-align: center;"><%= link_to('<i class="icon-edit"'.html_safe, edit_mailing_path(m), :title => "Edit this mailing.") %></td>
        <td style="text-align: center;"><%= link_to('<i class="icon-remove"'.html_safe, m, :confirm => "Are you sure you want to delete this mailing?", :method => :delete, :title => "Delete this mailing.") %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/mailings/edit.html.erb
<h3>Edit <%= @mailing.subject %></h3>
<%= render('mailings/form') %>

app/views/mailings/index.html.erb
<h2>Spamalot! Mailing Campaigns</h2>
<%= render 'mailings/mailings_table', :campaigns => @mailings %>
<%= link_to("Add a New Mailing", new_mailing_path, :class => "btn btn-primary") %>
<button id="clientTest">Test Client Message</button>

app/views/mailings/index.js.erb
$('#content').html("<h2>IT CAME FROM JS!</h2><%= escape_javascript(render('mailings/mailings_table', :campaigns => @mailings)) %>");

app/views/mailings/new.html.erb
<h3>Create a new Spamalot! Mailing Campaign</h3>
<%= render('mailings/form') %>